#!/bin/csh -f
# run_cyclic_lif.csh -- Phase 1D Step 3 cyclic-LIF sweep driver
#
# Substitutes @V_erase@, @tdr@, @tdrdat@, @plot@, @log@ in
# ../sdevice_simH3_cyclic.cmd into per-node preprocessed cmd files,
# then runs sdevice on each sequentially.
# Master template stays untouched.
#
# Sweep: V_erase in { -4.0  -6.0  -10.0 } V  (L3, -8 V outlier dropped per Step 2c)
# Tags:  cyclic_vm4  cyclic_vm6  cyclic_vm10
#
# Per-cycle protocol: 9-pulse fire (V_pgm=+2.0V) + 10ns ramp to V_erase
#   + 10us hold at V_erase + 10ns ramp to -0.5V + 70us relax  =>  ~82us/cycle
# Total per node: 5 cycles = ~410 us sim time
#
# Acceptance:
#   M1: |drift_c3->c5| <= 1.0 %/cycle on ID_p9
#   M2: fire_ratio >= 1.5 every cycle vs in-cycle pre-burst baseline
#
# 2026-05-18

source $HOME/.cshrc

set SCRIPT_DIR = `dirname $0`
cd $SCRIPT_DIR/..      # run from GAAFet/ so n1_msh.tdr + sdevice_gaafet_lif.par resolve

set TEMPLATE = sdevice_simH3_cyclic.cmd   # regenerated by Simulations/_gen_h3_cyclic_cmd.py (2026-05-18); alignment-checked
set OUTDIR   = cyclic_lif_outputs
set GRID     = n1_msh.tdr

if ( ! -f $TEMPLATE ) then
    echo "ERROR: $TEMPLATE not found in `pwd`"
    exit 1
endif
if ( ! -f $GRID ) then
    echo "ERROR: $GRID not found in `pwd`"
    exit 1
endif

set V_LIST   = ( -4.0  -6.0  -10.0 )
set TAG_LIST = ( cyclic_vm4  cyclic_vm6  cyclic_vm10 )
set N        = $#V_LIST

echo "===================================================================="
echo "Phase 1D Step 3 cyclic-LIF sweep -- start `date '+%F %T'`"
echo "Working dir : `pwd`"
echo "Template    : $TEMPLATE"
echo "Output dir  : $OUTDIR"
echo "Nodes       : $N   (V_erase = $V_LIST V)"
echo "===================================================================="

# write sweep index
echo "# Phase 1D cyclic-LIF sweep  (2026-05-18)" > $OUTDIR/sweep_index.txt
@ k = 1
while ( $k <= $N )
    echo "  $TAG_LIST[$k]  ->  V_erase = $V_LIST[$k] V" >> $OUTDIR/sweep_index.txt
    @ k ++
end

@ i = 1
while ( $i <= $N )
    set V   = $V_LIST[$i]
    set TAG = $TAG_LIST[$i]
    set CMD = $OUTDIR/${TAG}_des.cmd
    set PLT = $OUTDIR/${TAG}_des.plt
    set TDR = $OUTDIR/${TAG}_des.tdr
    set LOG = $OUTDIR/${TAG}_des.log
    set RUN = $OUTDIR/${TAG}_runlog.txt

    echo ""
    echo "--------------------------------------------------------------------"
    echo "[`date '+%F %T'`]  node $i / $N   V_erase = $V V   tag = $TAG"
    echo "--------------------------------------------------------------------"

    sed \
        -e "s|@tdr@|$GRID|g" \
        -e "s|@tdrdat@|$TDR|g" \
        -e "s|@plot@|$PLT|g" \
        -e "s|@log@|$LOG|g" \
        -e "s|@V_erase@|$V|g" \
        $TEMPLATE > $CMD

    # guardrail: any @...@ left unsubstituted?
    set LEFT = `grep -c '@[A-Za-z_]*@' $CMD`
    if ( $LEFT != 0 ) then
        echo "  *** $LEFT unsubstituted placeholder(s) in $CMD -- aborting"
        grep -n '@[A-Za-z_]*@' $CMD
        exit 2
    endif

    sdevice $CMD >& $RUN
    set rc = $status
    if ( $rc != 0 ) then
        echo "  *** sdevice exited status $rc on $TAG"
        echo "  --- last 30 lines of $RUN ---"
        tail -n 30 $RUN
        echo "  *** aborting sweep at node $i"
        exit $rc
    endif
    echo "  ok   ($TAG done at `date '+%F %T'`)"
    @ i ++
end

echo ""
echo "===================================================================="
echo "All $N nodes complete -- `date '+%F %T'`"
echo "Outputs in $OUTDIR/{cyclic_vm4,cyclic_vm6,cyclic_vm10}_des.{plt,tdr,log}"
echo "===================================================================="
