
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2023.12                           ***
***                      (2.8515123, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2023 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'localhost' by user 'du'
Binary '/home/du/Sentaurus/sentaurus/V-2023.12/bin/../tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 --max_threads 1 -job 3 -swb_pid 76724 -gsub_pid 115371 -gsub_host localhost -gsub_port 43371 /home/du/Sentaurus-files/Sami_Hozaifa/GAAFet'
Current directory '/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/home/du/Sentaurus/sentaurus/V-2023.12/bin/..
	STRELEASE=current
	STROOT_LIB=/home/du/Sentaurus/sentaurus/V-2023.12/bin/../tcad/current/lib
	STDB=/home/du/Sentaurus-files
	DATEX=/home/du/Sentaurus/sentaurus/V-2023.12/bin/../tcad/current/lib/datexcodes.txt
	DISPLAY=localhost:10.0

Project '/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/gtree.dat'
Loading jobs and dependence graph '"/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/gexec.cmd"'
Loading project variables '/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/sdevice_des.cmd
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/sdevice_des.cmd for node 3
'@tdr@' creates dependences with the node(s) '1'
+++Preprocessing results written to /home/du/Sentaurus-files/Sami_Hozaifa/GAAFet/pp3_des.cmd
The node '3' has dependencies to the node(s) '1'
Start Simulation section
21:19:52 Mar 24 2026     job 3 <sdevice> started on host 'hostname1': "sdevice --max_threads 1  pp3_des.cmd"
21:21:34 Mar 24 2026 +++ job 3 <sdevice> done: exit(0)
End Simulation section
Start Epilogue section
21:21:34 Mar 24 2026 *** job 3 pre/post execution: eval " gjob::find_extracted_vars "/home/du/Sentaurus-files/Sami_Hozaifa/GAAFet" n3_des.out 3 "
End Epilogue section
Job succeeded
gjob exits with status 0
