"""RR-6: Sentaurus Visual batch script for the 2D maps, band cuts and mesh figure.

No .tdr file exists anywhere in this project -- only .plt -- so there is not a
single 2D map, band diagram or mesh figure in the deck.  rrgen.tdr_states writes
a snapshot of the erased and the programmed retained state at V_G = 0; this
module turns those into the figures and, more importantly, into the CSVs behind
them, so the plots can be redrawn in matplotlib to match the rest of the paper
rather than living as svisual screenshots.

Emitted per state (erased / programmed):
  map_<state>_polarization.png    P_y across the whole stack
  map_<state>_edensity.png        electron density (the channel)
  map_<state>_efield.png          |E|, showing the SiO2 / HZO divider
  cut_v_<state>.csv               vertical cut at mid-channel: ConductionBand,
                                  ValenceBand, ElectricField/y, Polarization/y vs y
  cut_h_<state>.csv               horizontal cut along the channel: ConductionBand,
                                  ValenceBand, eDensity vs x
and once:
  mesh.png                        mesh density, for the methods figure

Run on the host:  svisual -b -f maps_vis.tcl
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

HEADER = """# RR-6 2D maps / band cuts / mesh -- generated by visgen.py, run with: svisual -b -f
lib::SetInfoDef 1
set OUT "vis_out"
file mkdir $OUT
"""

STATE = """
# ---------------------------------------------------------------- {state}
load_file {tdr} -name {state}
create_plot -dataset {state} -name P_{state}
select_plots P_{state}
windows_style -style max
set_window_full -on

foreach {{field tag}} {{ {fields} }} {{
    set_field_prop -plot P_{state} -field $field -type color_map -show_bands
    set_plot_prop -plot P_{state} -title "{state} : $field" -title_font_att bold
    export_view $OUT/map_{state}_$tag.png -format png -overwrite
}}

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cutv_{state} -plot P_{state} -type x -at 0]
export_variables {{ Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential \\
                   ElectricField-Y PolarizationVector-Y eDensity hDensity }} \\
    -dataset $cv -filename $OUT/cut_v_{state}.csv -overwrite

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name cuth_{state} -plot P_{state} -type y -at 0]
export_variables {{ X ConductionBandEnergy ValenceBandEnergy eDensity \\
                   ElectrostaticPotential }} \\
    -dataset $ch -filename $OUT/cut_h_{state}.csv -overwrite
"""

MESH = """
# ---------------------------------------------------------------- mesh figure
select_plots P_{state}
set_geom_prop -plot P_{state} -show_grid -show_interfaces
set_plot_prop -plot P_{state} -title "mesh density (channel refinement 0.5 nm)" \\
              -title_font_att bold
export_view $OUT/mesh.png -format png -overwrite
"""

FIELDS = ("PolarizationVector-Y polarization "
          "eDensity edensity "
          "ElectricField-Abs efield "
          "ConductionBandEnergy conductionband "
          "ElectrostaticPotential potential")


def gen(tdr_by_state):
    """tdr_by_state: {'erased': 'state_erased_t13_tdr_des.tdr', 'programmed': ...}"""
    s = HEADER
    first = None
    for state, tdr in tdr_by_state.items():
        first = first or state
        s += STATE.format(state=state, tdr=tdr, fields=FIELDS)
    s += MESH.format(state=first)
    return s


if __name__ == "__main__":
    tcl = gen({"erased": "state_erased_t13_tdr_des.tdr",
               "programmed": "state_programmed_t13_tdr_des.tdr"})
    (HERE / "vis").mkdir(exist_ok=True)
    (HERE / "vis" / "maps_vis.tcl").write_text(tcl)
    assert "@" not in tcl
    print(f"visgen OK: {len(tcl)} chars -> vis/maps_vis.tcl "
          f"({tcl.count('export_view')} images, {tcl.count('export_variables')} CSV cuts)")
