"""RR-6: extract the 2D maps and band cuts from the retained-state .tdr files.

No .tdr existed anywhere in this project until t13_tdr, so there was not a single
2D map, band diagram or mesh figure in the deck.  This module turns the erased
and programmed snapshots into CSVs, which are then plotted in matplotlib with the
same style as every other figure -- rather than shipping svisual screenshots that
cannot be restyled or re-plotted.

Two things about this host, both learned the hard way:

  * `svisual -b -f` does NOT run a Sentaurus Visual script.  `-f` is short for
    `-inspect`, i.e. "execute as an INSPECT script" -- a different tool with a
    different command language, which is why the script appeared to load and then
    silently did nothing.  The correct flag is `-s` / `-script`.
  * `-b` is pure batch and cannot export graphics; `-bx` can, but needs Xvfb,
    which is not installed here.  So no `export_view` -- no PNGs from svisual at
    all.  Only `export_variables`, which is what we actually want.

Dataset names in this TDR (confirmed by exporting, since `list_variables`
returns empty in batch mode): `ElectricField-Y`, `Polarization-Y`,
`ConductionBandEnergy`, `ValenceBandEnergy`, `ElectrostaticPotential`,
`eDensity`, `hDensity`, `SpaceCharge`, `DopingConcentration`.  Note it is
`Polarization-Y`, not `PolarizationVector-Y`.

Emitted per state (erased / programmed), into opt_outputs/vis_out/:
  cut_v_<state>.csv   vertical cut at mid-channel: bands, potential, E_y, P_y,
                      carrier densities vs y -- the gate-stack band diagram and
                      the SiO2/HZO field divider
  cut_h_<state>.csv   horizontal cut along the channel: bands, eDensity vs x
  map_<state>_x*.csv  a stack of 47 vertical cutlines on a 5 nm x grid, which
                      reassemble into the 2D colour maps (P_y, eDensity, |E|)

Run:  svisual -b -s maps_vis.tcl     (from the directory holding the .tdr files)
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

CUT_V = ("Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential "
         "ElectricField-Y Polarization-Y eDensity hDensity SpaceCharge")
CUT_H = ("X ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential "
         "eDensity hDensity")
# The 2D map is assembled from a STACK of vertical cutlines rather than one
# whole-dataset export: `export_variables -dataset <name>` on the full dataset
# returns "Could not retrieve data from dataset", and a cutline stack lands on a
# regular grid anyway, which plots better than scattered mesh nodes.
MAP = ("Y Polarization-Y ElectricField-Y ElectrostaticPotential "
       "ConductionBandEnergy eDensity hDensity SpaceCharge")
# Device x extent is -0.1 .. +0.1 um (source start to drain end); a cutline
# placed outside it returns an empty dataset and aborts the whole script.
MAP_X = [round(-0.098 + 0.004 * i, 4) for i in range(50)]   # -0.098 .. +0.098 um

HEADER = """# RR-6 band cuts and 2D field maps -- generated by visgen.py
# run with:  svisual -b -s maps_vis.tcl     (NOT -f, and NOT -bx: no Xvfb here)
file mkdir vis_out
"""

STATE = """
# ---------------------------------------------------------------- {state}
load_file {tdr} -name {state}
create_plot -dataset {state} -name P_{state}
select_plots P_{state}

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cv_{state} -plot P_{state} -type x -at 0]
export_variables {{ {cut_v} }} -dataset $cv \\
    -filename vis_out/cut_v_{state}.csv -overwrite
puts "DONE cut_v_{state}"

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name ch_{state} -plot P_{state} -type y -at 0]
export_variables {{ {cut_h} }} -dataset $ch \\
    -filename vis_out/cut_h_{state}.csv -overwrite
puts "DONE cut_h_{state}"

# 2D map: a stack of vertical cutlines on a regular 5 nm x grid
set i 0
foreach x {{ {map_x} }} {{
    set c [create_cutline -name m_{state}_$i -plot P_{state} -type x -at $x]
    export_variables {{ {map} }} -dataset $c \\
        -filename vis_out/map_{state}_[format %03d $i].csv -overwrite
    incr i
}}
puts "DONE map_{state}"
"""


def gen(tdr_by_state):
    """tdr_by_state: {'erased': 'state_erased_t13_tdr_des.tdr', 'programmed': ...}"""
    s = HEADER
    for state, tdr in tdr_by_state.items():
        s += STATE.format(state=state, tdr=tdr, cut_v=CUT_V, cut_h=CUT_H,
                          map=MAP, map_x=' '.join(str(x) for x in MAP_X))
    return s


if __name__ == "__main__":
    tcl = gen({"erased": "state_erased_t13_tdr_des.tdr",
               "programmed": "state_programmed_t13_tdr_des.tdr"})
    (HERE / "vis").mkdir(exist_ok=True)
    (HERE / "vis" / "maps_vis.tcl").write_text(tcl, newline="\n")
    assert "@" not in tcl
    assert "export_view" not in tcl, "no Xvfb on this host -- svisual cannot export images"
    assert " -f " not in tcl
    print(f"visgen OK: {len(tcl)} chars -> vis/maps_vis.tcl "
          f"({tcl.count('export_variables')} CSV exports, 0 images by design)")
