# RR-6 band cuts and 2D field maps -- generated by visgen.py
# run with:  svisual -b -s maps_vis.tcl     (NOT -f, and NOT -bx: no Xvfb here)
file mkdir vis_out

# ---------------------------------------------------------------- erased
load_file state_erased_t13_tdr_des.tdr -name erased
create_plot -dataset erased -name P_erased
select_plots P_erased

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cv_erased -plot P_erased -type x -at 0]
export_variables { Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential ElectricField-Y Polarization-Y eDensity hDensity SpaceCharge } -dataset $cv \
    -filename vis_out/cut_v_erased.csv -overwrite
puts "DONE cut_v_erased"

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name ch_erased -plot P_erased -type y -at 0]
export_variables { X ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential eDensity hDensity } -dataset $ch \
    -filename vis_out/cut_h_erased.csv -overwrite
puts "DONE cut_h_erased"

# 2D map: a stack of vertical cutlines on a regular 5 nm x grid
set i 0
foreach x { -0.098 -0.094 -0.09 -0.086 -0.082 -0.078 -0.074 -0.07 -0.066 -0.062 -0.058 -0.054 -0.05 -0.046 -0.042 -0.038 -0.034 -0.03 -0.026 -0.022 -0.018 -0.014 -0.01 -0.006 -0.002 0.002 0.006 0.01 0.014 0.018 0.022 0.026 0.03 0.034 0.038 0.042 0.046 0.05 0.054 0.058 0.062 0.066 0.07 0.074 0.078 0.082 0.086 0.09 0.094 0.098 } {
    set c [create_cutline -name m_erased_$i -plot P_erased -type x -at $x]
    export_variables { Y Polarization-Y ElectricField-Y ElectrostaticPotential ConductionBandEnergy eDensity hDensity SpaceCharge } -dataset $c \
        -filename vis_out/map_erased_[format %03d $i].csv -overwrite
    incr i
}
puts "DONE map_erased"

# ---------------------------------------------------------------- programmed
load_file state_programmed_t13_tdr_des.tdr -name programmed
create_plot -dataset programmed -name P_programmed
select_plots P_programmed

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cv_programmed -plot P_programmed -type x -at 0]
export_variables { Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential ElectricField-Y Polarization-Y eDensity hDensity SpaceCharge } -dataset $cv \
    -filename vis_out/cut_v_programmed.csv -overwrite
puts "DONE cut_v_programmed"

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name ch_programmed -plot P_programmed -type y -at 0]
export_variables { X ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential eDensity hDensity } -dataset $ch \
    -filename vis_out/cut_h_programmed.csv -overwrite
puts "DONE cut_h_programmed"

# 2D map: a stack of vertical cutlines on a regular 5 nm x grid
set i 0
foreach x { -0.098 -0.094 -0.09 -0.086 -0.082 -0.078 -0.074 -0.07 -0.066 -0.062 -0.058 -0.054 -0.05 -0.046 -0.042 -0.038 -0.034 -0.03 -0.026 -0.022 -0.018 -0.014 -0.01 -0.006 -0.002 0.002 0.006 0.01 0.014 0.018 0.022 0.026 0.03 0.034 0.038 0.042 0.046 0.05 0.054 0.058 0.062 0.066 0.07 0.074 0.078 0.082 0.086 0.09 0.094 0.098 } {
    set c [create_cutline -name m_programmed_$i -plot P_programmed -type x -at $x]
    export_variables { Y Polarization-Y ElectricField-Y ElectrostaticPotential ConductionBandEnergy eDensity hDensity SpaceCharge } -dataset $c \
        -filename vis_out/map_programmed_[format %03d $i].csv -overwrite
    incr i
}
puts "DONE map_programmed"
