# RR-6 2D maps / band cuts / mesh -- generated by visgen.py, run with: svisual -b -f
lib::SetInfoDef 1
set OUT "vis_out"
file mkdir $OUT

# ---------------------------------------------------------------- erased
load_file state_erased_t13_tdr_des.tdr -name erased
create_plot -dataset erased -name P_erased
select_plots P_erased
windows_style -style max
set_window_full -on

foreach {field tag} { PolarizationVector-Y polarization eDensity edensity ElectricField-Abs efield ConductionBandEnergy conductionband ElectrostaticPotential potential } {
    set_field_prop -plot P_erased -field $field -type color_map -show_bands
    set_plot_prop -plot P_erased -title "erased : $field" -title_font_att bold
    export_view $OUT/map_erased_$tag.png -format png -overwrite
}

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cutv_erased -plot P_erased -type x -at 0]
export_variables { Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential \
                   ElectricField-Y PolarizationVector-Y eDensity hDensity } \
    -dataset $cv -filename $OUT/cut_v_erased.csv -overwrite

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name cuth_erased -plot P_erased -type y -at 0]
export_variables { X ConductionBandEnergy ValenceBandEnergy eDensity \
                   ElectrostaticPotential } \
    -dataset $ch -filename $OUT/cut_h_erased.csv -overwrite

# ---------------------------------------------------------------- programmed
load_file state_programmed_t13_tdr_des.tdr -name programmed
create_plot -dataset programmed -name P_programmed
select_plots P_programmed
windows_style -style max
set_window_full -on

foreach {field tag} { PolarizationVector-Y polarization eDensity edensity ElectricField-Abs efield ConductionBandEnergy conductionband ElectrostaticPotential potential } {
    set_field_prop -plot P_programmed -field $field -type color_map -show_bands
    set_plot_prop -plot P_programmed -title "programmed : $field" -title_font_att bold
    export_view $OUT/map_programmed_$tag.png -format png -overwrite
}

# vertical cut through the gate stack at mid-channel (x = 0)
set cv [create_cutline -name cutv_programmed -plot P_programmed -type x -at 0]
export_variables { Y ConductionBandEnergy ValenceBandEnergy ElectrostaticPotential \
                   ElectricField-Y PolarizationVector-Y eDensity hDensity } \
    -dataset $cv -filename $OUT/cut_v_programmed.csv -overwrite

# horizontal cut along the channel (y = 0, the middle of the 5 nm body)
set ch [create_cutline -name cuth_programmed -plot P_programmed -type y -at 0]
export_variables { X ConductionBandEnergy ValenceBandEnergy eDensity \
                   ElectrostaticPotential } \
    -dataset $ch -filename $OUT/cut_h_programmed.csv -overwrite

# ---------------------------------------------------------------- mesh figure
select_plots P_erased
set_geom_prop -plot P_erased -show_grid -show_interfaces
set_plot_prop -plot P_erased -title "mesh density (channel refinement 0.5 nm)" \
              -title_font_att bold
export_view $OUT/mesh.png -format png -overwrite
